apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaminarayan-timeline-timeline
  namespace: swaminarayan-timeline
spec:
  replicas: 1  # Reduced for shared cluster resources
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: timeline
        image: ghcr.io/khushal1198/swaminarayan-timeline-timeline:main-9000948
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule"