# First, create the SecretStore that connects to AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: tracc
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: tracc-external-secrets-sa
---
# External Secret for database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: tracc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: tracc/rds/credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: tracc/rds/credentials
        property: password
---
# External Secret for OAuth credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-credentials
  namespace: tracc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: tracc/oauth/google
        property: client_id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: tracc/oauth/google
        property: client_secret
    - secretKey: FACEBOOK_CLIENT_ID
      remoteRef:
        key: tracc/oauth/facebook
        property: client_id
    - secretKey: FACEBOOK_CLIENT_SECRET
      remoteRef:
        key: tracc/oauth/facebook
        property: client_secret
---
# External Secret for JWT signing key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: tracc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: tracc/jwt/secret
        property: secret_key
---
# External Secret for GHCR (GitHub Container Registry) credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: tracc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .token }}",
                "auth": "{{ printf "%s:%s" .username .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: tracc/ghcr/credentials
        property: username
    - secretKey: token
      remoteRef:
        key: tracc/ghcr/credentials
        property: token
---
# ServiceAccount for External Secrets to access AWS
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracc-external-secrets-sa
  namespace: tracc