# External Secrets configuration for Swaminarayan Timeline
# Uses the tracc IAM role and GHCR credentials from AWS Secrets Manager

# SecretStore for K3s - uses EC2 instance profile (no JWT auth needed)
# NOTE: This is deleted by kustomize overlay - K3s uses ClusterSecretStore instead
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: swaminarayan-timeline
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # No auth section - K3s uses node IAM role via EC2 instance profile
---
# External Secret for GHCR (GitHub Container Registry) credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: swaminarayan-timeline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .token }}",
                "auth": "{{ printf "%s:%s" .username .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: tracc/ghcr/credentials
        property: username
    - secretKey: token
      remoteRef:
        key: tracc/ghcr/credentials
        property: token
---
# ServiceAccount - Not needed for K3s (uses EC2 instance profile)
# NOTE: This is deleted by kustomize overlay
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracc-external-secrets-sa
  namespace: swaminarayan-timeline
