# External Secrets configuration for Swaminarayan Timeline
# Uses the tracc IAM role and GHCR credentials from AWS Secrets Manager

# SecretStore for accessing AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: swaminarayan-timeline
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: tracc-external-secrets-sa
---
# External Secret for GHCR (GitHub Container Registry) credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: swaminarayan-timeline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .token }}",
                "auth": "{{ printf "%s:%s" .username .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: tracc/ghcr/credentials
        property: username
    - secretKey: token
      remoteRef:
        key: tracc/ghcr/credentials
        property: token
---
# ServiceAccount referencing the tracc IAM role for AWS access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracc-external-secrets-sa
  namespace: swaminarayan-timeline
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::883669803269:role/tracc-external-secrets-role
