# Patch ExternalSecret to use ClusterSecretStore instead of namespace SecretStore
# K3s uses EC2 instance profile authentication, not IRSA
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
