# Patch all ExternalSecrets to use ClusterSecretStore instead of namespace SecretStore
# K3s uses EC2 instance profile authentication, not IRSA
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: tracc/rds/credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: tracc/rds/credentials
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: oauth-credentials
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: tracc/oauth/google
        property: client_id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: tracc/oauth/google
        property: client_secret
    - secretKey: FACEBOOK_CLIENT_ID
      remoteRef:
        key: tracc/oauth/facebook
        property: client_id
    - secretKey: FACEBOOK_CLIENT_SECRET
      remoteRef:
        key: tracc/oauth/facebook
        property: client_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: tracc/jwt/secret
        property: secret_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .token }}",
                "auth": "{{ printf \"%s:%s\" .username .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: tracc/ghcr/credentials
        property: username
    - secretKey: token
      remoteRef:
        key: tracc/ghcr/credentials
        property: token
