apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ui-root-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /static/index.html
spec:
  rules:
    - host: shivi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-ui-service
                port:
                  number: 80
    - host: ui.shivi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-ui-service
                port:
                  number: 80 