# Ingress for the UI service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-grpc-ingress
  namespace: default # Explicitly in the default namespace
  annotations:
    # Specify which Ingress controller to use
    kubernetes.io/ingress.class: "traefik"
    # Use middleware for redirect
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-static@kubernetescrd
spec:
  rules:
  - host: ui.shivi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-ui-service
            port:
              number: 80
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: hello-ui-service
            port:
              number: 80 