apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: shivi.local  # Changed from hello-grpc.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-ui-service
            port:
              number: 80
      - path: /hello-grpc
        pathType: Prefix
        backend:
          service:
            name: hello-ui-service
            port:
              number: 80 