apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ui-server
  labels:
    app: hello-ui-server
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-ui-server
  template:
    metadata:
      labels:
        app: hello-ui-server
    spec:
      containers:
      - name: ui-server
        image: ghcr.io/khushal1198/hello_grpc-ui:master-7af3be3
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: APP_ENV
          value: "PROD"
        - name: GRPC_SERVER_HOST
          value: "hello-grpc-service"
        - name: GRPC_SERVER_PORT
          value: "50051"
        - name: USER_SERVICE_HOST
          value: "hello-grpc-user-service"
        - name: USER_SERVICE_PORT
          value: "50052"
        - name: EXPENSE_SERVICE_HOST
          value: "hello-grpc-expense-service"
        - name: EXPENSE_SERVICE_PORT
          value: "50053"
        - name: UI_SERVER_PORT
          value: "8081"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-ui-service
  labels:
    app: hello-ui-server
spec:
  selector:
    app: hello-ui-server
  ports:
  - port: 80
    targetPort: 8081
    name: http
  type: ClusterIP
