apiVersion: apps/v1
kind: Deployment
metadata:
  name: isso-sf-content
  namespace: isso-sf
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: content
        image: ghcr.io/khushal1198/isso_sf-content:main-4c0d6fe
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
