name: Update Kubernetes Secrets

on:
  push:
    branches: [ main ]
    paths:
      - 'hello-grpc/**'
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          # Setup kubeconfig - adjust this based on your cluster setup
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Create imagePullSecret in cluster
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.GHCR_USERNAME }} \
            --docker-password=${{ secrets.GHCR_PAT }} \
            --docker-email=${{ secrets.GHCR_USERNAME }}@users.noreply.github.com \
            --namespace=default \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Verify secret creation
        run: |
          kubectl get secret ghcr-secret -n default
          echo "✅ Docker registry secret created/updated successfully"

      - name: Wait for ArgoCD sync
        run: |
          echo "🔄 Secret created. ArgoCD will sync deployments shortly..."
          echo "⏳ Allowing time for ArgoCD to detect and apply changes..."
          sleep 30 